/*
 * This source file was generated by the Gradle 'init' task
 */
package practicefinal2;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class PracticeTest {
    @Test
    void testOdd(){
        Practice practice = new Practice();
        int[] data = {1, 2, 3, 4, 5};
        assertEquals(practice.foobar(data), false);
    }

    @Test
    void testEven(){
        Practice practice = new Practice();
        int[] data = {1, 2, 3, 4};
        assertEquals(practice.foobar(data), true);
    }

    @Test
    void testEmpty(){
        Practice practice = new Practice();
        int[] data = {};
        assertEquals(practice.foobar(data), true);
    }

    @Test
    void testNegatives(){
        Practice practice = new Practice();
        int[] data = {-1, 2, 3, 4, 5};
        assertEquals(practice.foobar(data), false);
    }
}
